apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-backup-scripts
  namespace: esb
data:
  backup.sh: |
    #!/bin/bash

    # Variables
    NAMESPACE="esb"
    POD_NAME="reports-sftp"
    PVC_PATH="/home"
    BUCKET_NAME="aig-sftp-bucket"
    TIMESTAMP=$(date +%Y%m%d%H%M%S)
    BACKUP_FILE="backup-$TIMESTAMP.tar.gz"
    GCS_PATH="gs://$BUCKET_NAME/"

    # Crear el archivo tar.gz del contenido de /home
    kubectl exec -n $NAMESPACE $POD_NAME -- tar -czf /tmp/$BACKUP_FILE -C $PVC_PATH .

    # Copiar el archivo tar.gz al bucket de Google Cloud Storage
    kubectl cp $NAMESPACE/$POD_NAME:/tmp/$BACKUP_FILE /tmp/$BACKUP_FILE
    gsutil cp /tmp/$BACKUP_FILE $GCS_PATH

    # Eliminar el archivo temporal
    rm /tmp/$BACKUP_FILE
    kubectl exec -n $NAMESPACE $POD_NAME -- rm /tmp/$BACKUP_FILE

    # Eliminar archivos más antiguos de 7 días en el bucket
    gsutil ls -l $GCS_PATH | awk '{print $2}' | grep -v "^TOTAL:" | while read -r line; do
        FILE_DATE=$(echo $line | awk -F'.' '{print $1}' | awk -F'-' '{print $NF}')
        if [[ $FILE_DATE -lt $(date --date="7 days ago" +%Y%m%d%H%M%S) ]]; then
            gsutil rm "$GCS_PATH$line"
        fi
    done

